spring.application.name=Authorization-Generator


spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${MYSQL_HOST:localhost}:5432/postgresql
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect  # Dialeto do PostgreSQL
